---
title: "Dados de opiniões sobre filmes"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2, warn.conflicts = FALSE)
library(resample)

theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
read <- function(file) {
  #' Lê um csv criado a partir dos dados de gastos dos deputados da
  require("readr")

  file = read_csv(file, col_types = list(.default = col_character()))
  return(file)
}

get_database <- function() {
  #' Trabalha os dados de forma mais convenientemente para resolver o problema.
  require("dplyr", warn.conflicts = FALSE)
  
  movies = read("datasets/movies/movies.csv")
  rating = read("datasets/movies/rating.csv")
  
  dataframe = rating %>% 
    select(-userId, -timestamp) %>% left_join(movies, by = c("movieId" = "movieId")) %>%
    rowwise() %>% 
    mutate(countGen = length(unlist(strsplit(genres, '[|]'))), title = unlist(strsplit(as.character(title), " \\(.*\\)")))
  
  return(dataframe)
}

```

1. Qual dos episódios de Exterminator do Futuro (Terminator) é melhor avaliado e para qual possui mais variação em suas notas.

```{r}
base = get_database()

t1.dat = base %>% filter(title == "Terminator, The")

t2.dat = base %>% filter(title == "Terminator 2: Judgment Day")

t3.dat = base %>% filter(title == "Terminator 3: Rise of the Machines")
```


```{r}
t1.boot = bootstrap(t1.dat, mean(as.numeric(t1.dat$rating)), R = 10000)
mean.t1 = CI.percentile(t1.boot, probs = c(.025, .975))

t2.boot = bootstrap(t2.dat, mean(as.numeric(t2.dat$rating)), R = 10000)
mean.t2 = CI.percentile(t2.boot, probs = c(.025, .975))

t3.boot = bootstrap(t3.dat, mean(as.numeric(t3.dat$rating)), R = 10000)
mean.t3 = CI.percentile(t3.boot, probs = c(.025, .975))
```

```{r}
df = data.frame(rbind(mean.t1, mean.t2, mean.t3))
df$mean = c("The Terminator", "Terminator 2: Judgment Day", "Terminator 3: Rise of the Machines")

df %>% 
  ggplot(aes(x = reorder(mean, c(1, 2, 3)), ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2) + 
  xlab("Mean of Rating")
```

